### ISSUE TITLE
Potential naming conflict.

### ISSUE THREAD

**Issue by amcgregor** [Stentle/laravel-web-core#1]
Howdy!

I'm the maintainer of the Python [WebCore web framework](https://github.com/marrow/webcore) (see the master branch commit history) and got a neat Google Alert today that you've bundled up a package similarly called ["webcore" on Packagist](https://packagist.org/packages/stentle/webcore).  My WebCore has been in production use since 2009.  Your package is quite new and… seems to be an API binding?

What shall we do about the conflict, if anything?  :)

Have a great day,
— Alice.

**Comment by giuseppetoto** [comment]
Hello,

I read your request, but do not understand the problem. Packages are
identified by the vendor / name combination and not only by the name so in
my case "stentle / Webcore" and your case "marrow/ webcore" . Also the name
"Webcore" is generic not to recall or identify any vendor in particular.

I am also willing to change your name if you make me better understand the
problem, to avoid further conflicts with other vendors.

Thank you
Giuseppe

2016-03-17 18:32 GMT+01:00 Alice Zoë Bevan–McGregor <
notifications@github.com>:

**Comment by amcgregor** [comment]
1. Unfortunately, packages under other management systems do not use Github account prefixes.  For example, Gentoo ebuilds, making this a `dev-libs/webcore` conflict there.  (That's just one example, though.  Python's Package Index similarly doesn't use prefixes, etc., etc.)

2. It pollutes internet searches for the term with multiple competing web development software packages (common problem domain); the WebCore web framework is currently ranked 4th on Duckduckgo (better for testing as it doesn't personalize result ordering) and is beaten only by unrelated companies whose names are similar who probably did some SEO work to their sites.  (And Apple's WebKit, because Apple. ;)

Obviously I can't force you to change the name, but it would be package-neighbourly of you.  ^_^  Thank you for your consideration.

**Comment by giuseppetoto** [comment]
Our package is only available on Packagist repository in which the distinction is clear vendor / name, therefore it is impossible that we create conflict with other repositories.

Also if you look at the other package made by major vendors, we note that common names are used. Eg:
Symfony / CONSOLE
sebastian / VERSION
Symfony / TRANSLATION
etc.

However it has not yet spread our package I'll try to accommodate your request, hoping not to have some other vendors require me to once again change the name :)

**Comment by amcgregor** [comment]
Thank you again.  I feel your pain; the entire Marrow collective used to be called "pulp" (as a tongue-in-cheek poke at a competing package collective named "paste"), but there was a conflict…  ^_^;
